name: Rust CI

on:
  push:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Clippy Check
        run: cargo clippy --all-targets -- -D warnings

      - name: Run Tests
        run: cargo test --all
